package net.geraldhofbauer.vanillaplusadditions.modules.battle_dogs.compat.quark;

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import net.geraldhofbauer.vanillaplusadditions.modules.battle_dogs.item.WolfArmorItem;
import net.minecraft.client.model.geom.EntityModelSet;
import net.minecraft.client.renderer.MultiBufferSource;
import net.minecraft.client.renderer.RenderType;
import net.minecraft.client.renderer.entity.RenderLayerParent;
import net.minecraft.client.renderer.entity.layers.RenderLayer;
import net.minecraft.client.renderer.texture.OverlayTexture;
import net.minecraft.world.item.ItemStack;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.api.distmarker.OnlyIn;
import org.violetmoon.quark.base.client.handler.ModelHandler;
import org.violetmoon.quark.content.mobs.client.model.FoxhoundModel;
import org.violetmoon.quark.content.mobs.entity.Foxhound;

/**
 * Draws our four armour tiers on Quark's Foxhound.
 *
 * <p>Quark ships an armour layer of its own, but it never fires for our armour: it is gated on
 * {@code Wolf.hasArmor()}, which is {@code getBodyArmorItem().is(Items.WOLF_ARMOR)} - the concrete
 * vanilla item, not the type. A foxhound wearing one of ours therefore showed nothing at all, while
 * the inventory slot quite plainly held a set of armour. Our own wolf layer could not step in
 * either: it is bound to {@code EntityType.WOLF}'s renderer, and the Foxhound has its own.</p>
 *
 * <p>The geometry comes from Quark ({@code ModelHandler.foxhound_armor}, a 64×64 layout of its
 * own), the colour from us. The four textures are generated by
 * {@code scripts/gen_foxhound_armor_textures.py}, which recolours Quark's own armour texture with
 * each tier's palette - see that script for why recolouring, and not reusing the wolf texture, is
 * the only thing that can work across two different UV layouts.</p>
 *
 * <p>No crack overlay. Vanilla's {@code wolf_armor_crackiness_*} textures are laid out for the
 * 64×32 wolf armour model and would smear across this one; a damaged set simply stays clean here.
 * Quark's own layer has the same problem and maps to the same vanilla textures.</p>
 */
@OnlyIn(Dist.CLIENT)
public class FoxhoundArmorLayer extends RenderLayer<Foxhound, FoxhoundModel> {

    private final FoxhoundModel model;

    public FoxhoundArmorLayer(RenderLayerParent<Foxhound, FoxhoundModel> parent, EntityModelSet models) {
        super(parent);
        this.model = new FoxhoundModel(models.bakeLayer(ModelHandler.foxhound_armor));
    }

    @Override
    public void render(PoseStack poseStack, MultiBufferSource buffer, int packedLight,
                       Foxhound foxhound, float limbSwing, float limbSwingAmount, float partialTick,
                       float ageInTicks, float netHeadYaw, float headPitch) {
        if (foxhound.isInvisible()) {
            return;
        }

        ItemStack stack = foxhound.getBodyArmorItem();
        if (!(stack.getItem() instanceof WolfArmorItem wolfArmor)) {
            return;
        }

        this.getParentModel().copyPropertiesTo(this.model);
        this.model.prepareMobModel(foxhound, limbSwing, limbSwingAmount, partialTick);
        this.model.setupAnim(foxhound, limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch);

        VertexConsumer consumer = buffer.getBuffer(
                RenderType.entityCutoutNoCull(wolfArmor.getFoxhoundTexture()));
        this.model.renderToBuffer(poseStack, consumer, packedLight, OverlayTexture.NO_OVERLAY);
    }
}
